sudo: required
services:
  - docker

before_install:
  - docker build -t nyquist22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nyquist22/react-test npm test -- --coverage

after_success:
  - docker build -t nyquist22/multi-client ./client
  - docker build -t nyquist22/multi-server ./server
  - docker build -t nyquist22/multi-nginx ./nginx
  - docker build -t nyquist22/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nyquist22/multi-client
  - docker push nyquist22/multi-server
  - docker push nyquist22/multi-nginx
  - docker push nyquist22/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: elasticbeanstalk-us-east-2-056931149014
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
